# Generated by Django 5.1.6 on 2025-04-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userhistory_delete_detectionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='truncated_content',
        ),
    ]
